{{- if (hasKey .Values "certmanager") and .Values.certmanager.enabled }}
{{- if eq .Values.certmanager.production "false" }}
apiVersion: certmanager.k8s.io/v1alpha1
kind: Certificate
metadata:
  name: "tls-{{ .Values.cluster.domain | replace "." "-" }}-s"
spec:
  secretName: "tls-{{ .Values.cluster.domain | replace "." "-" }}-s"
  issuerRef:
    name: letsencrypt-staging
  commonName: "*.{{ .Values.cluster.domain }}"
  dnsNames:
  - "*.{{ .Values.cluster.domain }}"
{{- if hasKey .Values "additionalSolvers" }}
{{- range .Values.additionalSolvers }}
{{- range .domains }}
  - {{ . | quote }}
{{- end }}
{{- end }}
{{- end }}
{{- end }}
{{- end }}
